import { z } from "zod";
import { isScryptHash } from "../auth/password-format.js";
import {
  ALLOWED_IMAGE_EXTENSIONS_LABEL,
  isAllowedImageFilename,
} from "../images/formats.js";
import { ISO_DATE_PATTERN } from "../schedule/calendar-date.js";

export const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

const nonEmpty = z.string().trim().min(1, "Must not be empty");
const optionalNonEmpty = nonEmpty.optional();

export const appConfigSchema = z.strictObject({
  site: z.strictObject({
    title: nonEmpty,
    password: z.string().trim().optional(),
    timezone: nonEmpty,
  }),
  admin: z.strictObject({
    passwordHash: z
      .string()
      .refine(
        isScryptHash,
        "Must be a scrypt hash generated by npm run hash-password",
      ),
  }),
  people: z.record(
    z.string(),
    z.strictObject({
      name: nonEmpty,
      image: z
        .string()
        .refine(
          isAllowedImageFilename,
          `Must be a filename with a ${ALLOWED_IMAGE_EXTENSIONS_LABEL} extension`,
        )
        .optional(),
    }),
  ),
  gameNights: z.array(
    z.strictObject({
      id: z.string().regex(SLUG_PATTERN, "Must be a lowercase slug"),
      name: nonEmpty,
      password: z.string().trim().optional(),
      description: optionalNonEmpty,
      anchorDate: z
        .string()
        .regex(ISO_DATE_PATTERN, "Must be an ISO date (YYYY-MM-DD)"),
      intervalDays: z.number().int().positive(),
      people: z.array(z.string()).min(1, "Must contain at least one person"),
    }),
  ),
  overrides: z
    .array(
      z.strictObject({
        gameNight: z.string(),
        date: z
          .string()
          .regex(ISO_DATE_PATTERN, "Must be an ISO date (YYYY-MM-DD)"),
        person: z.string(),
        reason: optionalNonEmpty,
      }),
    )
    .default([]),
  dateOverrides: z
    .array(
      z.strictObject({
        gameNight: z.string(),
        oldDate: z
          .string()
          .regex(ISO_DATE_PATTERN, "Must be an ISO date (YYYY-MM-DD)"),
        newDate: z
          .string()
          .regex(ISO_DATE_PATTERN, "Must be an ISO date (YYYY-MM-DD)"),
      }),
    )
    .default([]),
  extraDays: z
    .array(
      z.strictObject({
        gameNight: z.string(),
        date: z
          .string()
          .regex(ISO_DATE_PATTERN, "Must be an ISO date (YYYY-MM-DD)"),
        reason: optionalNonEmpty,
      }),
    )
    .default([]),
});
